### ISSUE TITLE
Difference with lm-evaluation-harness

### ISSUE THREAD

**Issue by merlinarer** [lm-pub-quiz/lm-pub-quiz#8]
hello, I would like to know the difference with [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness), which also uses a similar ppl evaluation for multiple choice datasets.

**Comment by plonerma** [comment]
Hello @merlinarer, thanks for your question and sorry for answering so late.

You are right – there are some similarities between lm-pub-quiz and lm-evaluation-harness. However, there are also some key differences why we decided to implement a separate framework:

1. Probably the biggest difference lies in lm-pub-quiz's support of of masked language models.
2. We enable templates where the answer (or object of the relation) to be in any position of the template, not necessarily as part of a continuation. The BEAR dataset could probably be adapted to work with lm-evaluation-harness. However, 
3. a big part of lm-pub-quiz is the preprocessing which generates the statements from the item table (which we are planning to extend in the future).

We have discussed providing an harness-compatible [BEAR](https://github.com/lm-pub-quiz/BEAR) version to make its use easier for people using harness already, but unfortunately haven't gotten around to that yet.

In any case, with BEAR we aimed to make knowledge-evaluation across MLM and CLM models and build lm-pub-quiz to make this as easy as possible for other users.
